
Adapt.@adapt_structure FiniteTimeReward
Adapt.@adapt_structure InfiniteTimeReward
Adapt.@adapt_structure Specification
Adapt.@adapt_structure VerificationProblem
Adapt.@adapt_structure ControlSynthesisProblem
